version: '3'
services:
  wp_mysql_local:
    container_name: wp_mysql_local
    image: mysql:5.7.22
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wpLocal
      - MYSQL_USER=wp
      - MYSQL_PASSWORD=password
